### ISSUE TITLE
View Files macro isn't showing the selected files

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/xwiki-pro-macros#240]
Issue probably related to https://github.com/xwikisas/xwiki-pro-macros/issues/136 and https://github.com/xwikisas/xwiki-pro-macros/issues/180

Preconditions:
The office server needs to be configured and connected to the XWiki instance. Add attachments to the page used (doc, docx, xls, xlsx, ppt, pptx, and pdf) that have special characters in the title.

Steps to reproduce:

1. Edit a page
2. Click on Insert > Other macros 
3. Search and select View Files
4. In the "att--filename" text box add the name of a file from the attachments section, including the file extension ex.:

- [Te$t with #special + ch@rs - test. It's ^a test! Test ~1 = and (2) & {3}, [4]. 100% a test 1; 2` 3; 5.pdf](https://github.com/xwikisas/xwiki-pro-macros/files/14996904/Te.t.with.special.%2B.ch%40rs.-.test.It.s.a.test.Test.1.and.2.3.4.100.a.test.1.2.3.5.pdf)
- [Te$t with #special + ch@rs - test. It's ^a test! Test ~1 = and (2) & {3}, [4]. 100% a test 1; 2` 3; 5.pptx](https://github.com/xwikisas/xwiki-pro-macros/files/14996912/Te.t.with.special.%2B.ch%40rs.-.test.It.s.a.test.Test.1.and.2.3.4.100.a.test.1.2.3.5.pptx)
- [Te$t with #special + ch@rs - test. It's ^a test! Test ~1 = and (2) & {3}, [4]. 100% a test 1; 2` 3; 5.docx](https://github.com/xwikisas/xwiki-pro-macros/files/14996915/Te.t.with.special.%2B.ch%40rs.-.test.It.s.a.test.Test.1.and.2.3.4.100.a.test.1.2.3.5.docx)
5. Click on Submit
6. Click on Save & View

Expected results: The document selected is shown in the wiki page. The supported file types are doc, docx, xls, xlsx, ppt, pptx, and pdf.

Actual results: The file isn't shown, instead "Error: The document [xwiki:PRO Macros.View File.Te$t with #special ch] does not exists or you have no access to that document." appears.

![ViewFiles](https://github.com/xwikisas/xwiki-pro-macros/assets/40691112/f793f749-9575-4146-ad03-67f20175e898)

![ViewFilesDocs](https://github.com/xwikisas/xwiki-pro-macros/assets/40691112/943fae23-b5ac-439d-97bd-bf1e941b0107)

**NOTE:** Same issue when using the following macros: View Doc, View Pdf, View Ppt, View Xls""

In the wiki console:
`2024-04-16 15:23:03,635 [XWiki Solr index thread] ERROR .PackageRelationshipCollection - Cannot convert %5b1%5d%20http:/creativecommons.org/licenses/by-nc-sa/4.0/ in a valid relationship URI-> dummy-URI used
java.net.URISyntaxException: Illegal character in scheme name at index 0: %5b1%5d%20http:/creativecommons.org/licenses/by-nc-sa/4.0/
        at java.base/java.net.URI$Parser.fail(URI.java:2974)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3145)
        at java.base/java.net.URI$Parser.checkChar(URI.java:3155)
        at java.base/java.net.URI$Parser.parse(URI.java:3170)
        at java.base/java.net.URI.<init>(URI.java:623)
        at org.apache.poi.openxml4j.opc.PackagingURIHelper.toURI(PackagingURIHelper.java:723)
        at org.apache.poi.openxml4j.opc.PackageRelationshipCollection.parseRelationshipsPart(PackageRelationshipCollection.java:358)
        at org.apache.poi.openxml4j.opc.PackageRelationshipCollection.<init>(PackageRelationshipCollection.java:160)
        at org.apache.poi.openxml4j.opc.PackageRelationshipCollection.<init>(PackageRelationshipCollection.java:130)
        at org.apache.poi.openxml4j.opc.PackagePart.loadRelationships(PackagePart.java:565)
        at org.apache.poi.openxml4j.opc.OPCPackage.getParts(OPCPackage.java:751)
        at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:322)
        at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:127)
        at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:118)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:203)
        at org.apache.tika.Tika.parseToString(Tika.java:525)
        at org.apache.tika.Tika.parseToString(Tika.java:495)
        at org.xwiki.tika.internal.TikaUtils.parseToString(TikaUtils.java:153)
        at org.xwiki.search.solr.internal.metadata.AbstractSolrMetadataExtractor.getContentAsText(AbstractSolrMetadataExtractor.java:534)
        at org.xwiki.search.solr.internal.metadata.DocumentSolrMetadataExtractor.setAttachment(DocumentSolrMetadataExtractor.java:333)
        at org.xwiki.search.solr.internal.metadata.DocumentSolrMetadataExtractor.setAttachments(DocumentSolrMetadataExtractor.java:313)
        at org.xwiki.search.solr.internal.metadata.DocumentSolrMetadataExtractor.setExtras(DocumentSolrMetadataExtractor.java:239)
        at org.xwiki.search.solr.internal.metadata.DocumentSolrMetadataExtractor.setFieldsInternal(DocumentSolrMetadataExtractor.java:152)
        at org.xwiki.search.solr.internal.metadata.AbstractSolrMetadataExtractor.getSolrDocument(AbstractSolrMetadataExtractor.java:171)
        at org.xwiki.search.solr.internal.DefaultSolrIndexer.lambda$getSolrDocument$0(DefaultSolrIndexer.java:525)
        at org.xwiki.bridge.internal.DefaultDocumentContextExecutor.call(DefaultDocumentContextExecutor.java:65)
        at org.xwiki.search.solr.internal.DefaultSolrIndexer.getSolrDocument(DefaultSolrIndexer.java:525)
        at org.xwiki.search.solr.internal.DefaultSolrIndexer.processBatch(DefaultSolrIndexer.java:428)
        at org.xwiki.search.solr.internal.DefaultSolrIndexer.run(DefaultSolrIndexer.java:393)
        at java.base/java.lang.Thread.run(Thread.java:842)
2024-04-16 15:23:04,832 [XWiki Solr index thread] WARN  o.a.p.h.m.t.BitMaskTextProp    - Style properties of 'paragraph_flags' don't match mask - output will be sanitized
2024-04-16 15:23:04,833 [XWiki Solr index thread] WARN  o.a.p.h.m.t.BitMaskTextProp    - Style properties of 'paragraph_flags' don't match mask - output will be sanitized
2024-04-16 15:23:04,833 [XWiki Solr index thread] WARN  o.a.p.h.m.t.BitMaskTextProp    - Style properties of 'paragraph_flags' don't match mask - output will be sanitized
2024-04-16 15:23:04,833 [XWiki Solr index thread] WARN  o.a.p.h.m.t.BitMaskTextProp    - Style properties of 'paragraph_flags' don't match mask - output will be sanitized
2024-04-16 15:23:04,834 [XWiki Solr index thread] WARN  o.a.p.h.m.t.BitMaskTextProp    - Style properties of 'paragraph_flags' don't match mask - output will be sanitized
2024-04-16 15:23:04,834 [XWiki Solr index thread] WARN  o.a.p.h.m.t.BitMaskTextProp    - Style properties of 'paragraph_flags' don't match mask - output will be sanitized
2024-04-16 15:23:04,834 [XWiki Solr index thread] WARN  o.a.p.h.m.t.BitMaskTextProp    - Style properties of 'paragraph_flags' don't match mask - output will be sanitized
2024-04-16 15:23:04,834 [XWiki Solr index thread] WARN  o.a.p.h.m.t.BitMaskTextProp    - Style properties of 'paragraph_flags' don't match mask - output will be sanitized
2024-04-16 15:23:04,835 [XWiki Solr index thread] WARN  o.a.p.h.m.t.BitMaskTextProp    - Style properties of 'paragraph_flags' don't match mask - output will be sanitized
2024-04-16 15:23:04,867 [XWiki Solr index thread] WARN  o.a.p.h.m.t.BitMaskTextProp    - Style properties of 'paragraph_flags' don't match mask - output will be sanitized
2024-04-16 15:23:04,869 [XWiki Solr index thread] WARN  o.a.p.h.m.t.BitMaskTextProp    - Style properties of 'paragraph_flags' don't match mask - output will be sanitized`

Environment: Windows 11, XWiki 14510.18, Chrome 123, Pro Macros 1.16.5

**Comment by snazare** [comment]
this seems to have been fixed by the most recent improvement on view-file. I tested with files with this name 
`[Te$t with #special ch@rs - test. It's ^a test! Test ~1 = and (2) & {3}, [4]. 100% a test 1; 2` 3; 5`

<img width="795" alt="view-file macro with special chars" src="https://github.com/user-attachments/assets/a23ee14d-dfba-457c-8764-b3d5a4446432">
